name: "CI"

on:
  push:
    branches: "**"
  pull_request:
    branches: "**"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x, 18.x, 19.x, 20.x]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: Setup pnpm
        uses: actions/setup-pnpm@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'
      - run: pnpm install
      - run: pnpm test
